[tool.poetry]
name = "whisper-cpp-python"
version = "0.1.0"
description = ""
authors = ["Carlos Cardoso Dias <carlosdias.dev@gmail.com>"]
readme = "README.md"
packages = [{include = "whisper_cpp_python"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
